// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview A flow for generating descriptions for AI models.
 *
 * - generateAiModelDescription - A function that generates a description for an AI model.
 * - GenerateAiModelDescriptionInput - The input type for the generateAiModelDescription function.
 * - GenerateAiModelDescriptionOutput - The return type for the generateAiModelDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAiModelDescriptionInputSchema = z.object({
  name: z.string().describe('The name of the AI model.'),
  type: z.string().describe('The type or category of the AI model (e.g., Large Language Model, Image Generation).'),
  developer: z.string().describe('The developer or organization behind the AI model.'),
  link: z.string().url().optional().describe('The official link to the AI model documentation or project page.'),
});
export type GenerateAiModelDescriptionInput = z.infer<typeof GenerateAiModelDescriptionInputSchema>;

const GenerateAiModelDescriptionOutputSchema = z.object({
  description: z.string().describe('A detailed and engaging description of the AI model.'),
});
export type GenerateAiModelDescriptionOutput = z.infer<typeof GenerateAiModelDescriptionOutputSchema>;

export async function generateAiModelDescription(input: GenerateAiModelDescriptionInput): Promise<GenerateAiModelDescriptionOutput> {
  return generateAiModelDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateAiModelDescriptionPrompt',
  input: {schema: GenerateAiModelDescriptionInputSchema},
  output: {schema: GenerateAiModelDescriptionOutputSchema},
  prompt: `You are an AI model expert. Generate a detailed and engaging description for the AI model based on the following information:

Name: {{{name}}}
Type: {{{type}}}
Developer: {{{developer}}}
{{#if link}}Link: {{{link}}}{{/if}}

The description should highlight the model's key capabilities, strengths, and potential use cases. It should be approximately 100-150 words long.
`,
});

const generateAiModelDescriptionFlow = ai.defineFlow(
  {
    name: 'generateAiModelDescriptionFlow',
    inputSchema: GenerateAiModelDescriptionInputSchema,
    outputSchema: GenerateAiModelDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
