// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview A flow for generating descriptions for AI tools.
 *
 * - generateAiToolDescription - A function that generates a description for an AI tool.
 * - GenerateAiToolDescriptionInput - The input type for the generateAiToolDescription function.
 * - GenerateAiToolDescriptionOutput - The return type for the generateAiToolDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAiToolDescriptionInputSchema = z.object({
  name: z.string().describe('The name of the AI tool.'),
  context: z.string().describe('The context or category of the AI tool (e.g., Chatbot, Image Generation).'),
  link: z.string().url().describe('The official link to the AI tool.'),
});
export type GenerateAiToolDescriptionInput = z.infer<typeof GenerateAiToolDescriptionInputSchema>;

const GenerateAiToolDescriptionOutputSchema = z.object({
  description: z.string().describe('A detailed and engaging description of the AI tool.'),
});
export type GenerateAiToolDescriptionOutput = z.infer<typeof GenerateAiToolDescriptionOutputSchema>;

export async function generateAiToolDescription(input: GenerateAiToolDescriptionInput): Promise<GenerateAiToolDescriptionOutput> {
  return generateAiToolDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateAiToolDescriptionPrompt',
  input: {schema: GenerateAiToolDescriptionInputSchema},
  output: {schema: GenerateAiToolDescriptionOutputSchema},
  prompt: `You are an AI tool expert. Generate a detailed and engaging description for the AI tool based on the following information:

Name: {{{name}}}
Context: {{{context}}}
Link: {{{link}}}

The description should highlight the tool's key features, benefits, and use cases. It should be approximately 100-150 words long.
`,
});

const generateAiToolDescriptionFlow = ai.defineFlow(
  {
    name: 'generateAiToolDescriptionFlow',
    inputSchema: GenerateAiToolDescriptionInputSchema,
    outputSchema: GenerateAiToolDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
