import type { Tool, NewsArticle, AIModel } from '@/lib/types';

export const mockUser = {
  id: 'mock-user-123',
  email: 'user@example.com',
  displayName: 'Người dùng Demo',
  photoURL: 'https://placehold.co/100x100.png',
};

export const mockTools: Tool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    context: 'Chatbot',
    ranking: 1,
    description: 'Mô hình ngôn ngữ hàng đầu của OpenAI, có khả năng tạo văn bản giống người dựa trên gợi ý.',
    logoUrl: 'https://images.unsplash.com/photo-1562783912-21ad31ee2a83?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxsb2dvJTIwY29tcGFueXxlbnwwfHx8fDE3NDkzNzU4NTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    link: 'https://chat.openai.com',
    features: ['Hiểu ngôn ngữ tự nhiên', 'Tạo văn bản', 'Tạo mã nguồn', 'Dịch thuật'],
    userRating: 4.8,
    isFavorite: false,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    context: 'AI Đa phương thức',
    ranking: 2,
    description: 'Mô hình AI thế hệ tiếp theo của Google, được thiết kế để có tính đa phương thức tự nhiên và khả năng cao.',
    logoUrl: 'https://images.unsplash.com/photo-1496200186974-4293800e2c20?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxsb2dvJTIwY29tcGFueXxlbnwwfHx8fDE3NDkzNzU4NTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    link: 'https://deepmind.google/technologies/gemini/',
    features: ['Hiểu văn bản, hình ảnh, âm thanh, video', 'Lý luận nâng cao', 'Tạo mã nguồn'],
    userRating: 4.7,
    isFavorite: true,
  },
  {
    id: 'claude',
    name: 'Claude 3',
    context: 'Chatbot',
    ranking: 3,
    description: 'Một dòng các mô hình ngôn ngữ lớn được phát triển bởi Anthropic, tập trung vào tính an toàn và hữu ích.',
    logoUrl: 'https://images.unsplash.com/photo-1529612700005-e35377bf1415?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxsb2dvJTIwY29tcGFueXxlbnwwfHx8fDE3NDkzNzU4NTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    link: 'https://www.anthropic.com/claude',
    features: ['AI hội thoại', 'Tóm tắt nội dung', 'Viết sáng tạo'],
    userRating: 4.6,
    isFavorite: false,
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    context: 'Tạo hình ảnh',
    ranking: 4,
    description: 'Một phòng nghiên cứu độc lập sản xuất chương trình trí tuệ nhân tạo độc quyền tạo ra hình ảnh từ mô tả văn bản.',
    logoUrl: 'https://images.unsplash.com/photo-1554049697-02e809699995?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxsb2dvJTIwY29tcGFueXxlbnwwfHx8fDE3NDkzNzU4NTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    link: 'https://www.midjourney.com',
    features: ['Tạo hình ảnh chất lượng cao', 'Phong cách nghệ thuật', 'Sáng tạo dựa trên gợi ý'],
    userRating: 4.9,
    isFavorite: true,
  },
  {
    id: 'n8n',
    name: 'n8n',
    context: 'Tự động hóa',
    ranking: 5,
    description: 'Công cụ tự động hóa quy trình làm việc dựa trên node, miễn phí và mã nguồn mở. Dễ dàng tự động hóa các tác vụ trên các dịch vụ khác nhau.',
    logoUrl: 'https://placehold.co/64x64.png?text=N8N',
    link: 'https://n8n.io/',
    features: ['Tự động hóa quy trình làm việc', 'No-code/low-code', 'Tích hợp có thể mở rộng'],
    userRating: 4.5,
  },
   {
    id: 'make',
    name: 'Make (Integromat)',
    context: 'Tự động hóa',
    ranking: 6,
    description: 'Một nền tảng tích hợp mạnh mẽ cho phép bạn hình dung, thiết kế và tự động hóa công việc của mình trong vài phút.',
    logoUrl: 'https://placehold.co/64x64.png?text=MK',
    link: 'https://www.make.com/',
    features: ['Trình xây dựng quy trình làm việc trực quan', 'Nhiều tích hợp ứng dụng', 'Tự động hóa tác vụ'],
    userRating: 4.3,
  },
  {
    id: 'tavily',
    name: 'Tavily AI',
    context: 'API Tìm kiếm',
    ranking: 7,
    description: 'Một API tìm kiếm được hỗ trợ bởi AI dành cho nhà phát triển, cung cấp kết quả tìm kiếm thời gian thực, chính xác và toàn diện.',
    logoUrl: 'https://placehold.co/64x64.png?text=TVL',
    link: 'https://tavily.com/',
    features: ['Tìm kiếm thời gian thực', 'Kết quả được tối ưu hóa bằng AI', 'Tích hợp API dễ dàng'],
    userRating: 4.4,
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    context: 'Hỗ trợ viết',
    description: 'Tích hợp AI vào không gian làm việc Notion để hỗ trợ viết, tóm tắt và lên ý tưởng.',
    logoUrl: 'https://placehold.co/64x64.png?text=NAI',
    link: 'https://www.notion.so/product/ai',
    userRating: 4.2,
  }
];

export const mockAIModels: AIModel[] = [
  {
    id: 'gpt-4',
    name: 'GPT-4',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'Mô hình đa phương thức lớn nhất của OpenAI, có khả năng giải quyết các vấn đề khó khăn với độ chính xác cao hơn, nhờ kiến thức tổng quát rộng hơn và khả năng lý luận tiên tiến.',
    logoUrl: 'https://placehold.co/64x64.png?text=G4',
    link: 'https://openai.com/gpt-4',
    userRating: 4.9,
    features: ['Lý luận nâng cao', 'Hiểu biết đa phương thức (văn bản, hình ảnh)', 'Khả năng sáng tạo và cộng tác'],
  },
  {
    id: 'gemini-pro',
    name: 'Gemini Pro',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Google',
    description: 'Mô hình mạnh mẽ nhất của Google cho một loạt các tác vụ, vượt trội trong lý luận, tạo mã và hiểu đa phương thức.',
    logoUrl: 'https://placehold.co/64x64.png?text=GMP',
    link: 'https://deepmind.google/technologies/gemini/#introduction',
    userRating: 4.8,
    features: ['Đa phương thức (văn bản, mã, hình ảnh, video)', 'Hiệu suất cao trên nhiều lĩnh vực', 'Tối ưu hóa cho khả năng mở rộng'],
  },
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Anthropic',
    description: 'Mô hình mạnh mẽ nhất của Anthropic, mang lại hiệu suất hàng đầu cho các tác vụ rất phức tạp. Nó có thể điều hướng các gợi ý mở và các kịch bản chưa từng thấy với sự trôi chảy và hiểu biết giống như con người.',
    logoUrl: 'https://placehold.co/64x64.png?text=C3O',
    link: 'https://www.anthropic.com/news/claude-3-family',
    userRating: 4.85,
    features: ['Phân tích và dự báo nâng cao', 'Tạo nội dung tinh vi', 'Thị giác máy tính (xử lý hình ảnh)'],
  },
  {
    id: 'dall-e-3',
    name: 'DALL·E 3',
    type: 'Tạo hình ảnh',
    developer: 'OpenAI',
    description: 'Mô hình tạo hình ảnh mới nhất của OpenAI, có khả năng tạo ra hình ảnh rất chi tiết và chính xác từ mô tả văn bản.',
    logoUrl: 'https://placehold.co/64x64.png?text=DE3',
    link: 'https://openai.com/dall-e-3',
    userRating: 4.7,
    features: ['Hiểu rõ gợi ý phức tạp', 'Tạo hình ảnh chất lượng cao', 'Tích hợp với ChatGPT'],
  },
  {
    id: 'stable-diffusion-3',
    name: 'Stable Diffusion 3',
    type: 'Tạo hình ảnh',
    developer: 'Stability AI',
    description: 'Thế hệ tiếp theo của mô hình tạo hình ảnh mã nguồn mở từ Stability AI, hứa hẹn cải thiện đáng kể về chất lượng hình ảnh, hiểu gợi ý và khả năng tạo văn bản trong hình ảnh.',
    logoUrl: 'https://placehold.co/64x64.png?text=SD3',
    userRating: 4.6,
    features: ['Tạo hình ảnh từ văn bản', 'Chất lượng hình ảnh được cải thiện', 'Khả năng tạo văn bản trong hình ảnh'],
  }
];


export const mockNews: NewsArticle[] = [
  {
    id: 'news1',
    title: 'Claude 3 Opus Giành Vị trí Dẫn đầu trong Đấu trường AI, Vượt qua GPT-4',
    source: 'Anthropic',
    content: 'Mô hình mới nhất của Anthropic, Claude 3 Opus, đã chứng minh hiệu suất vượt trội trong các bài kiểm tra khác nhau, có khả năng vượt qua GPT-4 của OpenAI trong các lĩnh vực quan trọng về lý luận và kiến thức.',
    publishedAt: '2025-06-08T10:00:00Z',
    imageUrl: 'https://placehold.co/400x225.png',
    link: '#',
    dataAiHint: 'AI model'
  },
  {
    id: 'news2',
    title: 'Tương lai của AI trong Chăm sóc Sức khỏe: Dự đoán cho năm 2025',
    source: 'Tech Journal',
    content: 'Các chuyên gia dự đoán AI sẽ cách mạng hóa chẩn đoán, y học cá nhân hóa và khám phá thuốc trong vài năm tới, dẫn đến việc chăm sóc sức khỏe hiệu quả hơn.',
    publishedAt: '2025-06-07T14:30:00Z',
    imageUrl: 'https://placehold.co/400x225.png',
    link: '#',
    dataAiHint: 'AI healthcare'
  },
  {
    id: 'news3',
    title: 'AI Đạo đức: Điều hướng các Thách thức về Thiên vị và Minh bạch',
    source: 'AI Ethics Weekly',
    content: 'Khi các hệ thống AI ngày càng được tích hợp vào xã hội, việc giải quyết các vấn đề về thiên vị, công bằng và minh bạch là rất quan trọng để phát triển và triển khai có trách nhiệm.',
    publishedAt: '2025-06-06T09:15:00Z',
    imageUrl: 'https://placehold.co/400x225.png',
    link: '#',
    dataAiHint: 'AI ethics'
  },
];
