import type { Tool, NewsArticle } from '@/lib/types';

export const mockUser = {
  id: 'mock-user-123',
  email: 'user@example.com',
  displayName: 'Demo User',
  photoURL: 'https://placehold.co/100x100.png',
};

export const mockTools: Tool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    context: 'Chatbot',
    ranking: 1,
    description: 'Leading language model by OpenAI, capable of generating human-like text based on prompts.',
    logoUrl: 'https://placehold.co/64x64.png?text=GPT',
    link: 'https://chat.openai.com',
    features: ['Natural language understanding', 'Text generation', 'Code generation', 'Translation'],
    userRating: 4.8,
    isFavorite: false,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    context: 'Multimodal AI',
    ranking: 2,
    description: 'Google\'s next-generation AI model, designed to be natively multimodal and highly capable.',
    logoUrl: 'https://placehold.co/64x64.png?text=GMN',
    link: 'https://deepmind.google/technologies/gemini/',
    features: ['Text, image, audio, video understanding', 'Advanced reasoning', 'Code generation'],
    userRating: 4.7,
    isFavorite: true,
  },
  {
    id: 'claude',
    name: 'Claude 3',
    context: 'Chatbot',
    ranking: 3,
    description: 'A family of large language models developed by Anthropic, focused on safety and helpfulness.',
    logoUrl: 'https://placehold.co/64x64.png?text=CLD',
    link: 'https://www.anthropic.com/claude',
    features: ['Conversational AI', 'Content summarization', 'Creative writing'],
    userRating: 4.6,
    isFavorite: false,
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    context: 'Image Generation',
    ranking: 4,
    description: 'An independent research lab producing a proprietary artificial intelligence program that creates images from textual descriptions.',
    logoUrl: 'https://placehold.co/64x64.png?text=MJ',
    link: 'https://www.midjourney.com',
    features: ['High-quality image generation', 'Artistic styles', 'Prompt-based creation'],
    userRating: 4.9,
    isFavorite: true,
  },
  {
    id: 'n8n',
    name: 'n8n',
    context: 'Automation',
    ranking: 5,
    description: 'A free and open node-based Workflow Automation Tool. Easily automate tasks across different services.',
    logoUrl: 'https://placehold.co/64x64.png?text=N8N',
    link: 'https://n8n.io/',
    features: ['Workflow automation', 'No-code/low-code', 'Extensible integrations'],
    userRating: 4.5,
  },
   {
    id: 'make',
    name: 'Make (Integromat)',
    context: 'Automation',
    ranking: 6,
    description: 'A powerful integration platform that allows you to visualize, design, and automate your work in minutes.',
    logoUrl: 'https://placehold.co/64x64.png?text=MK',
    link: 'https://www.make.com/',
    features: ['Visual workflow builder', 'Wide range of app integrations', 'Task automation'],
    userRating: 4.6,
  },
  {
    id: 'tavily',
    name: 'Tavily AI',
    context: 'Search API',
    ranking: 7,
    description: 'An AI-powered search API for developers, providing real-time, accurate, and comprehensive search results.',
    logoUrl: 'https://placehold.co/64x64.png?text=TVL',
    link: 'https://tavily.com/',
    features: ['Real-time search', 'AI-optimized results', 'Easy API integration'],
    userRating: 4.4,
  },
];

export const mockNews: NewsArticle[] = [
  {
    id: 'news1',
    title: 'Claude 3 Opus Claims Top Spot in AI Arena, Surpassing GPT-4',
    source: 'Anthropic',
    content: 'Anthropic\'s latest model, Claude 3 Opus, has demonstrated superior performance in various benchmarks, potentially outperforming OpenAI\'s GPT-4 in key areas of reasoning and knowledge.',
    publishedAt: '2025-06-08T10:00:00Z',
    imageUrl: 'https://placehold.co/400x225.png',
    link: '#',
    dataAiHint: 'AI model'
  },
  {
    id: 'news2',
    title: 'The Future of AI in Healthcare: Predictions for 2025',
    source: 'Tech Journal',
    content: 'Experts predict AI will revolutionize diagnostics, personalized medicine, and drug discovery within the next few years, leading to more efficient and effective healthcare.',
    publishedAt: '2025-06-07T14:30:00Z',
    imageUrl: 'https://placehold.co/400x225.png',
    link: '#',
    dataAiHint: 'AI healthcare'
  },
  {
    id: 'news3',
    title: 'Ethical AI: Navigating the Challenges of Bias and Transparency',
    source: 'AI Ethics Weekly',
    content: 'As AI systems become more integrated into society, addressing issues of bias, fairness, and transparency is crucial for responsible development and deployment.',
    publishedAt: '2025-06-06T09:15:00Z',
    imageUrl: 'https://placehold.co/400x225.png',
    link: '#',
    dataAiHint: 'AI ethics'
  },
];
