
import type { AIModel } from '@/lib/types';

export const mockAIModels: AIModel[] = [
  {
    id: 'gpt-5-codex-high',
    name: 'GPT-5 Codex (high)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: `GPT-5 Codex (high) là mô hình AI thế hệ mới của OpenAI, ra mắt tháng 4 năm 2025, được tối ưu hóa đặc biệt cho các tác vụ lập trình. Với khả năng hiểu ngữ cảnh code phức tạp và tuân thủ hướng dẫn chặt chẽ, GPT-5 Codex (high) mang lại hiệu suất vượt trội, giúp các nhà phát triển tăng tốc độ làm việc và xây dựng các ứng dụng phức tạp một cách hiệu quả hơn.`,
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.5,
    ratingCount: 260,
    isFavorite: false,
    contextLengthToken: '400k',
    intelligenceScore: 68,
    pricePerMillionTokens: 3.44,
    speedTokensPerSecond: 171.6,
    latencyFirstChunkSeconds: 40.71,
  },
  {
    id: 'gpt-5-high',
    name: 'GPT-5 (high)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'GPT-5 (high) là phiên bản hiệu suất cao nhất của dòng mô hình GPT-5, được tối ưu hóa cho các tác vụ đòi hỏi sự chính xác và suy luận phức tạp. Nó cung cấp hiệu suất hàng đầu cho các ứng dụng doanh nghiệp quan trọng.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    contextLengthToken: '400k',
    intelligenceScore: 68,
    pricePerMillionTokens: 3.44,
    speedTokensPerSecond: 74.5,
    latencyFirstChunkSeconds: 122.57,
  },
  {
    id: 'grok-4',
    name: 'Grok 4',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'xAI',
    description: `+ Grok 4 là mô hình AI ngôn ngữ lớn (Large Language Model - LLM) mới nhất do công ty xAI của tỷ phú Elon Musk phát triển, được ra mắt vào tháng 7 năm 2025. Grok 4 đang nhận được rất nhiều quan tâm trong lĩnh vực AI với sự thông minh và các bài benchmark của nó vượt qua Open AI-04, Claude 4 và Gemini 2.5 pro.
+ Grok 4 đã sử dụng hệ thống siêu máy tính gồm hơn 200.000 GPU Nvidia H100 để huấn luyện (gấp đôi so với Grok 3) tất nhiên Grok 4 vẫn giữ được các ưu điểm của Grok 3 với tính năng DeepSearch cho phép truy xuất dữ liệu thời gian thực từ internet và mạng xã hội X, giúp nó cập nhật thông tin nhanh chóng và bắt kịp xu hướng mạng xã hội và vẫn tiếp tục hỗ trợ đa phương thức hình ảnh và văn bản tuy nhiên Grok 4 vẫn chưa hỗ trợ video và giọng nói.
+ Grok 4 tất nhiên vẫn hỗ trợ năng lực suy luận với Grok 4 Thinking và Grok 4 Heavy.
+ Một số người dùng và chuyên gia cho rằng Grok 4 có thể được thiết kế để phản ánh quan điểm chính trị cá nhân của Elon Musk khi trả lời các câu hỏi nhạy cảm, do mô hình tham khảo các bài đăng trên tài khoản X của Musk.`,
    logoUrl: '/image/Logo Grok cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.8,
    ratingCount: 190,
    contextLengthToken: '260K',
    intelligenceScore: 65,
    pricePerMillionTokens: 6,
    speedTokensPerSecond: 33.9,
    latencyFirstChunkSeconds: 18.74,
  },
  {
    id: 'gpt-5-medium',
    name: 'GPT-5 (medium)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'GPT-5 (medium) là phiên bản cân bằng giữa hiệu suất và tốc độ của dòng GPT-5, cung cấp khả năng mạnh mẽ với tốc độ phản hồi nhanh hơn, phù hợp cho nhiều ứng dụng tương tác.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    contextLengthToken: '400k',
    intelligenceScore: 66,
    pricePerMillionTokens: 3.44,
    speedTokensPerSecond: 98.6,
    latencyFirstChunkSeconds: 79.63,
  },
  {
    id: 'claude-4.5-sonnet-thinking',
    name: 'Claude 4.5 Sonnet Thinking',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Anthropic',
    description: `+ Claude 4.5 Sonnet là một trong hai phiên bản chủ lực của dòng mô hình Claude 4.5 do Anthropic ra mắt vào tháng 5 năm 2025, bên cạnh phiên bản Opus 4.5. Sonnet 4.5 được thiết kế để cân bằng giữa hiệu suất và chi phí, phù hợp với các ứng dụng cần khối lượng xử lý lớn, tốc độ phản hồi nhanh nhưng vẫn giữ được khả năng suy luận và lập trình nâng cao.
+ Claude 4.5 Sonnet là mô hình mạnh mẽ nhất của Claude 4.5 Sonnet với chức năng cho các nhiệm vụ phức tạp, giúp mô hình linh hoạt xử lý từ các câu hỏi nhanh đến các bài toán logic đa bước nhưng vẫn giữ được giá rẻ hơn 20% so với Claude 4.5 Opus.
+ Khi được cấp quyền truy cập file, Sonnet 4.5 có thể lưu trữ và trích xuất thông tin quan trọng để duy trì ngữ cảnh trong các dự án dài hạn như nghiên cứu hoặc phát triển phần mềm, giúp tăng tính liên tục và hiệu quả trong công việc.`,
    logoUrl: '/image/Logo Claude AI cho bảng xếp hạng.png',
    link: 'https://www.anthropic.com/news/claude-3-family',
    userRating: 4.5,
    ratingCount: 240,
    isFavorite: false,
    contextLengthToken: '1.0M',
    intelligenceScore: 63,
    pricePerMillionTokens: 6,
    speedTokensPerSecond: 59.2,
    latencyFirstChunkSeconds: 2.21,
  },
  {
    id: 'openai-o3',
    name: 'OpenAI o3',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: `+ OpenAI o3 là mô hình ngôn ngữ thế hệ mới do OpenAI phát triển, được ra mắt chính thức vào cuối năm 2024 như một bước tiến vượt bậc so với phiên bản tiền nhiệm o1. Đây là một mô hình transformer phản chiếu (reflective generative pre-trained transformer) được thiết kế đặc biệt để xử lý các câu hỏi đòi hỏi suy luận logic nhiều bước và tư duy phân tích sâu sắc.\n+ OpenAI o3 là một trong những mô hình đầu tiên của OpenAI có khả năng sử dụng công cụ một cách tự động trong quy trình suy luận, từ đó có thể truy cập thông tin thời gian thực, phân tích dữ liệu phức tạp và phối hợp nhiều khả năng để giải quyết các vấn đề đa bước hiệu quả hơn.\n+ OpenAI o3 đã áp dụng các kỹ thuật điều chỉnh và kiểm soát mới nhằm giảm thiểu các kết quả gây hại hoặc thiên lệch, đồng thời nâng cao tính minh bạch trong quá trình suy luận của mô hình.\n+ Mô hình cũng được tích hợp trong các dịch vụ như ChatGPT, API, Playground.`,
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.9,
    ratingCount: 350,
    isFavorite: false,
    contextLengthToken: '200k',
    intelligenceScore: 65,
    pricePerMillionTokens: 3.5,
    speedTokensPerSecond: 109.2,
    latencyFirstChunkSeconds: 14.11,
  },
  {
    id: 'gpt-5-low',
    name: 'GPT-5 (low)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'GPT-5 (low) là phiên bản giá rẻ của dòng GPT-5, được thiết kế cho các ứng dụng không yêu cầu hiệu suất cao nhất nhưng cần một giải pháp kinh tế và hiệu quả.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    contextLengthToken: '400K',
    intelligenceScore: 62,
    pricePerMillionTokens: 3.44,
    speedTokensPerSecond: 125,
    latencyFirstChunkSeconds: 26.63,
  },
  {
    id: 'gpt-oss-120b-high',
    name: 'GPT-oss-120B (high)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'GPT-oss-120B (high) là phiên bản hiệu suất cao của mô hình mã nguồn mở từ OpenAI, với 120 tỷ tham số. Nó được tối ưu hóa cho các tác vụ đòi hỏi sự chính xác cao và khả năng suy luận mạnh mẽ, trong khi vẫn duy trì các lợi ích của việc là một mô hình "open-weight".',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    contextLengthToken: '131k',
    intelligenceScore: 61,
    pricePerMillionTokens: 0.26,
    speedTokensPerSecond: 383,
    latencyFirstChunkSeconds: 0.38,
  },
  {
    id: 'gpt-5-mini-medium',
    name: 'GPT-5 mini (medium)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'GPT-5 mini (medium) là phiên bản cân bằng của dòng GPT-5 mini, được tối ưu hóa cho tốc độ và chi phí, mang lại hiệu suất mạnh mẽ cho các ứng dụng yêu cầu phản hồi nhanh.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    contextLengthToken: '400K',
    intelligenceScore: 61,
    pricePerMillionTokens: 0.69,
    speedTokensPerSecond: 104.3,
    latencyFirstChunkSeconds: 23.97,
  },
  {
    id: 'grok-4-fast-reasoning',
    name: 'Grok 4 Fast (Reasoning)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'xAI',
    description: 'Grok 4 Fast (Reasoning) là phiên bản tốc độ cao của dòng Grok 4, được tối ưu hóa để cung cấp các phản hồi suy luận nhanh chóng mà không làm giảm đáng kể độ chính xác. Đây là giải pháp lý tưởng cho các ứng dụng đòi hỏi tương tác tức thì và xử lý khối lượng lớn các truy vấn.',
    logoUrl: '/image/Logo Grok cho bảng xếp hạng.png',
    link: 'https://x.ai/grok',
    contextLengthToken: '2.0M',
    intelligenceScore: 60,
    pricePerMillionTokens: 0.28,
    speedTokensPerSecond: 209.5,
    latencyFirstChunkSeconds: 2.96,
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Google',
    description: `+ Gemini 2.5 Pro (cập nhật mới nhất tháng 06/2025) là mô hình đa phương thức (multimodal) mạnh mẽ nhất trong dòng Gemini do Google phát triển.
+ Gemini 2.5 Pro có thể hiểu và tạo ra nội dung dữ liệu dựa trên nhiều đầu vào khác nhau như văn bản, hình ảnh, video, âm thanh.
+ Mô hình hỗ trợ tới 1 triệu token trong một lần nhập liệu (tương đương khoảng 1,5 triệu từ hoặc 5.000 trang văn bản), với kế hoạch mở rộng lên 2 triệu token trong tương lai gần.Nhờ vậy, Gemini 2.5 Pro có thể xử lý các tài liệu dài, mã nguồn lớn (hơn 50.000 dòng code), video dài gần 1 giờ hoặc âm thanh lên đến 19 giờ trong một lần tương tác duy nhất.
+ Bạn có thể dùng thử Gemini 2.5 Pro ở trên Google AI Studio, Vertex AI, Gemini API.Ngoài ra, Gemini 2.5 Pro cũng được tích hợp trong ứng dụng Gemini dành cho người dùng cao cấp, với các tính năng mới như tăng gấp đôi giới hạn truy vấn, hỗ trợ camera trực tiếp và chia sẻ màn hình trong tính năng Stream.`,
    logoUrl: '/image/Logo Gemini cho bảng xếp hạng.png',
    link: 'https://deepmind.google/technologies/gemini/#introduction',
    userRating: 4.9,
    ratingCount: 250,
    isFavorite: false,
    contextLengthToken: '1m',
    intelligenceScore: 60,
    pricePerMillionTokens: 3.44,
    speedTokensPerSecond: 157.7,
    latencyFirstChunkSeconds: 32.41,
  },
  {
    id: 'claude-4.5-sonnet',
    name: 'Claude 4.5 Sonnet',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Anthropic',
    description: `Claude 4.5 Sonnet là một trong hai phiên bản chủ lực của dòng mô hình Claude 4.5, được thiết kế để cân bằng giữa hiệu suất và chi phí, phù hợp với các ứng dụng cần khối lượng xử lý lớn, tốc độ phản hồi nhanh nhưng vẫn giữ được khả năng suy luận và lập trình nâng cao.`,
    logoUrl: '/image/Logo Claude AI cho bảng xếp hạng.png',
    link: 'https://www.anthropic.com/news/claude-3-family',
    userRating: 4.5,
    ratingCount: 240,
    isFavorite: false,
    contextLengthToken: '1M',
    intelligenceScore: 50,
    pricePerMillionTokens: 6.00,
    speedTokensPerSecond: 69.1,
    latencyFirstChunkSeconds: 2.24,
  },
  {
    id: 'deepseek-r1-jan25',
    name: 'DeepSeek R1 0528',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Deepseek',
    description: `+ DeepSeek R1-0528 là phiên bản nâng cấp mới nhất DeepSeek, được công bố vào tháng 5 năm 2025 và cũng là mô hình mã nguồn mở nên người dùng có thể triển khai cục bộ trên chính máy chủ của các bạn.
+ Phiên bản này đánh dấu bước tiến quan trọng trong khả năng suy luận sâu sắc, hiệu suất xử lý và tối ưu tài nguyên, giúp DeepSeek R1 có thể cạnh tranh trực tiếp cả về chất lượng và giá cả với các mô hình của Google và Open Al.
+ Không giống các mô hình "open-weight" nhưng hạn chế giấy phép (như LLaMA), DeepSeek R1 cho phép sử dụng thương mại, tùy chỉnh và triển khai tự do, khiến nó trở thành “trụ cột" mới cho các startup, nhà nghiên cứu, và ứng dụng Al độc lập.
+ Đổi lại là tốc độ sinh token khá chậm 28.6 token/s cho nên người dùng sẽ chờ đợi hơi lâu nhưng đó không là gì so với tiềm năng nó mang lại.`,
    logoUrl: '/image/Logo Deepseek cho bảng xếp hạng.png',
    link: 'https://www.deepseek.com/',
    userRating: 4.9,
    ratingCount: 155,
    contextLengthToken: '128k',
    intelligenceScore: 52,
    pricePerMillionTokens: 1.98,
    speedTokensPerSecond: 21.1,
    latencyFirstChunkSeconds: 3.32,
  },
  {
    id: 'deepseek-v3.1-terminus-reasoning',
    name: 'DeepSeek V3.1 Terminus (Reasoning)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Deepseek',
    description: `+ DeepSeek V3.1 Terminus (Reasoning) là phiên bản kế nhiệm trong dòng mô hình DeepSeek, được tối ưu hóa đặc biệt cho các tác vụ đòi hỏi khả năng suy luận phức tạp, ra mắt vào tháng 8 năm 2025. Đây là mô hình mã nguồn mở, cho phép người dùng tự do triển khai trên hạ tầng riêng.
+ Phiên bản này tập trung vào việc cải thiện khả năng suy luận logic và giải quyết vấn đề nhiều bước, giúp nó cạnh tranh hiệu quả với các mô hình hàng đầu từ Google và OpenAI.
+ Giống như các phiên bản trước, DeepSeek V3.1 cho phép sử dụng thương mại và tùy chỉnh, trở thành một lựa chọn hấp dẫn cho các doanh nghiệp và nhà phát triển muốn xây dựng các ứng dụng AI độc lập.
+ Mô hình này cân bằng giữa hiệu suất suy luận cao và tốc độ xử lý hợp lý, mang lại một giải pháp mạnh mẽ cho các ứng dụng chuyên sâu.`,
    logoUrl: '/image/Logo Deepseek cho bảng xếp hạng.png',
    link: 'https://www.deepseek.com/',
    userRating: 4.4,
    ratingCount: 177,
    isFavorite: false,
    contextLengthToken: '130K',
    intelligenceScore: 58,
    pricePerMillionTokens: 1.91,
    speedTokensPerSecond: 0,
    latencyFirstChunkSeconds: 0,
  },
  {
    id: 'gemini-2.5-flash-reasoning',
    name: 'Gemini 2.5 Flash (Reasoning)',
    type: 'AI Đa phương thức',
    developer: 'Google',
    description: `+ Gemini 2.5 Flash (Reasoning) cập nhật mới nhất là tháng 9-2025 là phiên bản nâng cấp của Gemini 2.0 Flash đặc biệt với chắc năng suy luận nâng cao (Reasoning) mang đến hiệu suất ở mức chấp nhận được kết hợp với chi phí và độ mượt mà.
+ Nâng cấp từ Gemini 2.0 flash nên độ dài ngữ cảnh (context window) ở mức 1 triệu token là mức trở nên bình thường đối với nhà Google.
+ Gemini 2.5 flash đặc biệt phù hợp với các ứng dụng chatbot hoặc web /app cần phản hồi nhanh mà vẫn giữ được sự thông minh. Vì vậy sẽ là đối thủ trực tiếp với Claude 4 Sonnet Thinking nhưng Claude 4 Sonnet có giá chát hơn hẳn.`,
    logoUrl: '/image/Logo Gemini cho bảng xếp hạng.png',
    link: 'https://deepmind.google/technologies/gemini/',
    userRating: 4.9,
    ratingCount: 195,
    contextLengthToken: '1.0M',
    intelligenceScore: 54,
    pricePerMillionTokens: 0.85,
    speedTokensPerSecond: 255,
    latencyFirstChunkSeconds: 15.61,
  },
  {
    id: 'grok-3-mini-reasoning-high',
    name: 'Grok 3 mini Reasoning (high)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'xAI',
    description: `+Grok 3 Mini là mô hình ngôn ngữ mini do xAI phát triển, tích hợp sâu với nền tảng X (Twitter). Phiên bản "Mini" của Grok 3 được tối ưu để giữ được khả năng tuyệt vời khi bật chế độ suy luận cao (reasoning (high)), trong khi vẫn đảm bảo tốc độ phản hồi nhanh và khả năng triển khai nhẹ hơn trên nhiều nền tảng.
+Triển khai linh hoạt: Nhờ dung lượng nhỏ hơn, Grok 3 Mini dễ dàng tích hợp trên nhiều nền tảng, từ web, di động đến các ứng dụng doanh nghiệp.
+ Grok 3 mini do có sự hỗ trợ từ mạng xã hội X (Twitter) từ đó có khả năng truy cập và cập nhật dữ liệu thời gian thực từ X, giúp cung cấp thông tin mới nhất và phù hợp với các sự kiện đang diễn ra .
+ Phong cách phản hồi tự nhiên, thân thiện được học từ những người dùng mạng xã hội X nên Grok 3 và Grok 3 mini được đánh giá rất cao với cách trả lời gần gũi, hài hước và dễ tiếp cận với người dùng Việt Nam.`,
    logoUrl: '/image/Logo Grok cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.8,
    ratingCount: 180,
    contextLengthToken: '1m',
    intelligenceScore: 57,
    pricePerMillionTokens: 0.35,
    speedTokensPerSecond: 103.3,
    latencyFirstChunkSeconds: 0.54,
  },
  {
    id: 'qwen3-235b-reasoning',
    name: 'Qwen3 235B A22B 2507 (reasoning)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Alibaba',
    description: `+ Qwen3 235B là mô hình ngôn ngữ lớn (LLM) mã nguồn mở với 235 tỷ tham số do Alibaba Cloud phát triển. Được phát hành vào tháng 7 năm 2025, Qwen3 nổi bật với khả năng xử lý đa phương thức và hiệu suất suy luận mạnh mẽ, đặc biệt trong các lĩnh vực lập trình và toán học.
+ Mô hình này được xây dựng trên kiến trúc Transformer và huấn luyện trên một tập dữ liệu khổng lồ, bao gồm cả văn bản và mã nguồn.
+ Qwen3 235B là một lựa chọn mạnh mẽ cho các nhà phát triển và doanh nghiệp muốn xây dựng các ứng dụng AI tiên tiến, tận dụng lợi thế của một mô hình mã nguồn mở với hiệu suất cao và chi phí hợp lý.`,
    logoUrl: '/image/Logo Qwen cho bảng xếp hạng.png',
    link: 'https://qwen.aliyun.com/',
    userRating: 4.6,
    ratingCount: 150,
    isFavorite: false,
    contextLengthToken: '260K',
    intelligenceScore: 57,
    pricePerMillionTokens: 2.63,
    speedTokensPerSecond: 74.9,
    latencyFirstChunkSeconds: 1.38,
  },
  {
    id: 'qwen3-vl-235b-a22b-reasoning',
    name: 'Qwen3 VL 235B A22B (Reasoning)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Alibaba',
    description: 'Qwen3 VL 235B A22B là phiên bản nâng cao trong dòng Qwen3, được tối ưu hóa cho khả năng suy luận và xử lý ngôn ngữ phức tạp. Với kiến trúc 235 tỷ tham số, mô hình này cung cấp hiệu suất vượt trội trong các tác vụ đòi hỏi sự hiểu biết sâu sắc về ngữ cảnh và logic.',
    logoUrl: '/image/Logo Qwen cho bảng xếp hạng.png',
    link: 'https://qwen.aliyun.com/',
    contextLengthToken: '260k',
    intelligenceScore: 54,
    pricePerMillionTokens: 2.63,
    speedTokensPerSecond: 42.3,
    latencyFirstChunkSeconds: 1.20,
  },
  {
    id: 'deepseek-v3.2-exp',
    name: 'DeepSeek V3.2 Exp',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'DeepSeek',
    description: `DeepSeek V3.2 Exp là phiên bản thử nghiệm mới nhất trong dòng mô hình DeepSeek, ra mắt vào cuối tháng 9 năm 2025. Đây là mô hình mã nguồn mở, cho phép người dùng tự do triển khai trên hạ tầng riêng. Phiên bản này tập trung vào việc cải thiện tốc độ và hiệu quả suy luận, trong khi vẫn duy trì được hiệu suất mạnh mẽ.`,
    logoUrl: '/image/Logo Deepseek cho bảng xếp hạng.png',
    link: 'https://www.deepseek.com/',
    contextLengthToken: '130K',
    intelligenceScore: 57,
    pricePerMillionTokens: 0.32,
    speedTokensPerSecond: 28.0,
    latencyFirstChunkSeconds: 1.12,
  },
  {
    id: 'claude-4.5-haiku-thinking',
    name: 'Claude 4.5 Haiku Thinking',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Anthropic',
    description: `+ Claude 4.5 Haiku Thinking là phiên bản cao cấp nhất trong dòng mô hình Claude 4 của Anthropic ( vừa ra mắt tháng 5 năm 2025) Claude Opus 4 được tối ưu đặc biệt cho các tác vụ đòi hỏi khả năng suy luận sâu với nhiều bước phức tạp đi kèm độ chính xác.
+ Claude 4.5 Haiku Thinking thật sự có lẽ là mô hình thông minh nhất hiện nay vì các lý do
+ Claude 4.5 Haiku có khả năng suy luận qua nhiều bước (multi-step reasoning), giúp mô hình xử lý vấn đề logic và có hệ thống, giảm tối đa"lối tắt" hay thủ thuật không những thế nó còn bổ sung chế độ Thinking cho phép mô hình tạm dừng để cân nhắc kỹ lưỡng nhiều bước trước khi đưa ra câu trả lời cuối cùng, điều đó giúp nó thông minh hơn 65% so với Claude 3.7 Sonnet.
+ Trong điểm thông minh ở đây không bổ sung benchmark như SWE-bench (78.3%) và Terminal-bench (85.2%) mà Claude 4.5 Haiku Thinking đạt được chứ không là nó bỏ xa các mô hình GPT-4.1 (54.6%) và Gemini 2.5 Pro (63.8%).
+ Claude 4.5 Haiku Thinking còn rất thân thiện và khả năng hoạt động ổn định với tiếng Việt. Mô hình này là ít lỗi nhất và ổn định nhất so với GPT 4.1 và Gemini 2.5 Pro nếu ai đã từng trải nghiệm nhưng có nhược điểm là giá rất cao vì vậy chỉ phù hợp với những ai có điều kiện và mô hình là doanh nghiệp.`,
    logoUrl: '/image/Logo Claude AI cho bảng xếp hạng.png',
    link: 'https://www.anthropic.com/news/claude-3-family',
    userRating: 4.9,
    ratingCount: 280,
    isFavorite: false,
    contextLengthToken: '200K',
    intelligenceScore: 55,
    pricePerMillionTokens: 2.00,
    speedTokensPerSecond: 43.0,
    latencyFirstChunkSeconds: 0.85,
  },
  {
    id: 'gpt-5-nano-high',
    name: 'GPT-5 nano (high)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'GPT-5 nano (high) là phiên bản nhỏ gọn và hiệu quả nhất trong dòng sản phẩm GPT-5, được tối ưu hóa cho tốc độ và chi phí vận hành. Với kiến trúc nhẹ, mô hình này mang lại khả năng phản hồi tức thì với độ trễ cực thấp, phù hợp cho các ứng dụng đòi hỏi xử lý khối lượng lớn và tương tác theo thời gian thực như chatbot hỗ trợ khách hàng, phân tích dữ liệu nhanh và các tác vụ tự động hóa quy mô lớn. Dù nhỏ gọn, GPT-5 nano vẫn duy trì được hiệu suất đáng kể, là một giải pháp kinh tế nhưng mạnh mẽ.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.5,
    ratingCount: 190,
    isFavorite: false,
    contextLengthToken: '400K',
    intelligenceScore: 51,
    pricePerMillionTokens: 0.14,
    speedTokensPerSecond: 104.5,
    latencyFirstChunkSeconds: 169.07,
  },
  {
    id: 'gpt-oss-20b-high',
    name: 'GPT-oss-20B (high)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'GPT-oss-20B (high) là phiên bản hiệu suất cao của mô hình mã nguồn mở 20 tỷ tham số từ OpenAI. Nó được tối ưu hóa cho các nhiệm vụ đòi hỏi độ chính xác cao và khả năng suy luận mạnh mẽ, trong khi vẫn duy trì các lợi ích của việc là một mô hình "open-weight", phù hợp cho việc triển khai trên phần cứng tiêu dùng.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.5,
    ratingCount: 225,
    isFavorite: false,
    contextLengthToken: '130k',
    intelligenceScore: 52,
    pricePerMillionTokens: 0.09,
    speedTokensPerSecond: 230.1,
    latencyFirstChunkSeconds: 0.32,
  },
  {
    id: 'qwen3-max',
    name: 'Qwen3 Max',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Alibaba',
    description: `Qwen3 Max là phiên bản mạnh mẽ nhất trong dòng mô hình Qwen3 của Alibaba, được tối ưu hóa để cung cấp hiệu suất cao nhất trong các tác vụ phức tạp. Với kiến trúc Transformer tiên tiến và được huấn luyện trên một tập dữ liệu khổng lồ, Qwen3 Max vượt trội trong các lĩnh vực đòi hỏi suy luận sâu, hiểu ngôn ngữ tự nhiên và khả năng lập trình nâng cao.`,
    logoUrl: '/image/Logo Qwen cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.9,
    ratingCount: 140,
    contextLengthToken: '260k',
    intelligenceScore: 55,
    pricePerMillionTokens: 2.4,
    speedTokensPerSecond: 33.7,
    latencyFirstChunkSeconds: 2.95,
  },
  {
    id: 'llama-nemotron-super-49b-v1-5-reasoning',
    name: 'Llama Nemotron Super 49B v1.5 (Reasoning)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Nvidia',
    description: `+ Llama Nemotron Super 49B v1.5 (Reasoning) là phiên bản cao cấp nhất trong dòng mô hình Llama Nemotron do NVIDIA phát triển, dựa trên nền tảng Llama 3.1 của Meta. Ra mắt đầu năm 2025, Nemotron Super được thiết kế đặc biệt để xử lý các tác vụ suy luận phức tạp, toán học nâng cao, lập trình và các nhiệm vụ khoa học với độ chính xác và hiệu suất vượt trội.
+ Mô hình được tối ưu đặc biệt cho hạ tầng GPU NVIDIA đa thiết bị, sử dụng các kỹ thuật như Neural Architecture Search (NAS) và Feed-Forward Network (FFN) Fusion giúp giảm đáng kể độ trễ và tăng thông lượng, đồng thời tiết kiệm bộ nhớ và chi phí vận hành trong môi trường trung tâm dữ liệu. Vì vậy cực kì thích hợp cho những cá nhân, công ty đang chạy phần cứng của Nvidia.
+ NVIDIA phát hành Llama Nemotron Super dưới giấy phép mở, cho phép doanh nghiệp và nhà phát triển sử dụng, tùy chỉnh và triển khai mô hình trong các ứng dụng thương mại với độ tin cậy cao.`,
    logoUrl: '/image/Logo Llama Nemotron Ultra Reasoning cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.9,
    ratingCount: 188,
    contextLengthToken: '130K',
    intelligenceScore: 45,
    pricePerMillionTokens: 0.17,
    speedTokensPerSecond: 77.9,
    latencyFirstChunkSeconds: 0.21,
  },
  {
    id: 'seed-oss-36b-instruct',
    name: 'Seed-OSS-36B-Instruct',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'ByteDance',
    description: `Seed-OSS-36B-Instruct là mô hình ngôn ngữ lớn mã nguồn mở do ByteDance phát triển, được công bố vào tháng 8 năm 2025. Với 36 tỷ tham số, mô hình này được thiết kế để cung cấp hiệu suất mạnh mẽ trong các tác vụ tuân thủ hướng dẫn và xử lý ngôn ngữ tự nhiên. Seed-OSS-36B-Instruct được huấn luyện trên một tập dữ liệu đa dạng và tối ưu hóa để hoạt động hiệu quả trên nhiều loại phần cứng, trở thành một lựa chọn hấp dẫn cho các nhà phát triển và doanh nghiệp muốn xây dựng các ứng dụng AI mạnh mẽ và tùy chỉnh.`,
    logoUrl: '/image/Logo-bytedance.png',
    link: 'https://www.bytedance.com/',
    userRating: 4.4,
    ratingCount: 160,
    isFavorite: false,
    contextLengthToken: '510K',
    intelligenceScore: 52,
    pricePerMillionTokens: 0.30,
    speedTokensPerSecond: 30.8,
    latencyFirstChunkSeconds: 1.71,
  },
];
    

    