
import type { Tool, NewsArticle, AIModel } from '@/lib/types';

export const mockUser = {
  id: 'mock-user-123',
  email: 'user@example.com',
  displayName: 'Người dùng Demo',
  photoURL: 'https://placehold.co/100x100.png',
};

export const mockTools: Tool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    context: 'Model AI', // Changed from 'Chatbot'
    ranking: 1,
    description: 'Mô hình ngôn ngữ hàng đầu của OpenAI, có khả năng tạo văn bản giống người dựa trên gợi ý.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://chat.openai.com',
    features: ['Hiểu ngôn ngữ tự nhiên', 'Tạo văn bản', 'Tạo mã nguồn', 'Dịch thuật'],
    userRating: 4.8,
    isFavorite: false,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    context: 'AI Đa phương thức',
    ranking: 2,
    description: 'Mô hình AI thế hệ tiếp theo của Google, được thiết kế để có tính đa phương thức tự nhiên và khả năng cao.',
    logoUrl: '/image/Logo Gemini cho bảng xếp hạng.png',
    link: 'https://deepmind.google/technologies/gemini/',
    features: ['Hiểu văn bản, hình ảnh, âm thanh, video', 'Lý luận nâng cao', 'Tạo mã nguồn'],
    userRating: 4.7,
    isFavorite: true,
  },
  {
    id: 'claude',
    name: 'Claude 3',
    context: 'Chatbot',
    ranking: 3,
    description: 'Một dòng các mô hình ngôn ngữ lớn được phát triển bởi Anthropic, tập trung vào tính an toàn và hữu ích.',
    logoUrl: '/image/Logo Claude AI cho bảng xếp hạng.png',
    link: 'https://www.anthropic.com/claude',
    features: ['AI hội thoại', 'Tóm tắt nội dung', 'Viết sáng tạo'],
    userRating: 4.6,
    isFavorite: false,
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    context: 'Tạo hình ảnh',
    ranking: 4,
    description: 'Một phòng nghiên cứu độc lập sản xuất chương trình trí tuệ nhân tạo độc quyền tạo ra hình ảnh từ mô tả văn bản.',
    logoUrl: 'https://images.unsplash.com/photo-1554049697-02e809699995?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxsb2dvJTIwY29tcGFueXxlbnwwfHx8fDE3NDkzNzU4NTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    link: 'https://www.midjourney.com',
    features: ['Tạo hình ảnh chất lượng cao', 'Phong cách nghệ thuật', 'Sáng tạo dựa trên gợi ý'],
    userRating: 4.9,
    isFavorite: true,
  },
  {
    id: 'n8n',
    name: 'n8n',
    context: 'Tự động hóa',
    ranking: 5,
    description: 'Công cụ tự động hóa quy trình làm việc dựa trên node, miễn phí và mã nguồn mở. Dễ dàng tự động hóa các tác vụ trên các dịch vụ khác nhau.',
    logoUrl: '/image/Logo n8n.png',
    link: 'https://n8n.io/',
    features: ['Tự động hóa quy trình làm việc', 'No-code/low-code', 'Tích hợp có thể mở rộng'],
    userRating: 4.5,
  },
   {
    id: 'make',
    name: 'Make (Integromat)',
    context: 'Tự động hóa',
    ranking: 6,
    description: 'Một nền tảng tích hợp mạnh mẽ cho phép bạn hình dung, thiết kế và tự động hóa công việc của mình trong vài phút.',
    logoUrl: 'https://placehold.co/64x64.png?text=MK',
    link: 'https://www.make.com/',
    features: ['Trình xây dựng quy trình làm việc trực quan', 'Nhiều tích hợp ứng dụng', 'Tự động hóa tác vụ'],
    userRating: 4.3,
  },
  {
    id: 'tavily',
    name: 'Tavily AI',
    context: 'API Tìm kiếm',
    ranking: 7,
    description: 'Một API tìm kiếm được hỗ trợ bởi AI dành cho nhà phát triển, cung cấp kết quả tìm kiếm thời gian thực, chính xác và toàn diện.',
    logoUrl: 'https://placehold.co/64x64.png?text=TVL',
    link: 'https://tavily.com/',
    features: ['Tìm kiếm thời gian thực', 'Kết quả được tối ưu hóa bằng AI', 'Tích hợp API dễ dàng'],
    userRating: 4.4,
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    context: 'Hỗ trợ viết',
    description: 'Tích hợp AI vào không gian làm việc Notion để hỗ trợ viết, tóm tắt và lên ý tưởng.',
    logoUrl: 'https://placehold.co/64x64.png?text=NAI',
    link: 'https://www.notion.so/product/ai',
    userRating: 4.2,
  },
  {
    id: 'stable-diffusion-3-tool',
    name: 'Stable Diffusion 3',
    context: 'Tạo hình ảnh',
    ranking: 8,
    description: 'Thế hệ tiếp theo của mô hình tạo hình ảnh mã nguồn mở từ Stability AI, hứa hẹn cải thiện đáng kể về chất lượng hình ảnh, hiểu gợi ý và khả năng tạo văn bản trong hình ảnh.',
    logoUrl: 'https://placehold.co/64x64.png?text=SD3T',
    link: 'https://stability.ai/stablediffusion3',
    features: ['Tạo hình ảnh từ văn bản', 'Chất lượng hình ảnh được cải thiện', 'Khả năng tạo văn bản trong hình ảnh', 'Mã nguồn mở'],
    userRating: 4.6,
    isFavorite: false,
  },
];

export const mockAIModels: AIModel[] = [
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Google',
    description: `+ Gemini 2.5 Pro (cập nhật mới nhất tháng 06/2025) là mô hình đa phương thức (multimodal) mạnh mẽ nhất trong dòng Gemini do Google phát triển.
+ Gemini 2.5 Pro có thể hiểu và tạo ra nội dung dữ liệu dựa trên nhiều đầu vào khác nhau như văn bản, hình ảnh, video, âm thanh.
+ Mô hình hỗ trợ tới 1 triệu token trong một lần nhập liệu (tương đương khoảng 1,5 triệu từ hoặc 5.000 trang văn bản), với kế hoạch mở rộng lên 2 triệu token trong tương lai gần.Nhờ vậy, Gemini 2.5 Pro có thể xử lý các tài liệu dài, mã nguồn lớn (hơn 50.000 dòng code), video dài gần 1 giờ hoặc âm thanh lên đến 19 giờ trong một lần tương tác duy nhất.
+ Bạn có thể dùng thử Gemini 2.5 Pro ở trên Google AI Studio, Vertex AI, Gemini API.Ngoài ra, Gemini 2.5 Pro cũng được tích hợp trong ứng dụng Gemini dành cho người dùng cao cấp, với các tính năng mới như tăng gấp đôi giới hạn truy vấn, hỗ trợ camera trực tiếp và chia sẻ màn hình trong tính năng Stream.`,
    logoUrl: '/image/Logo Gemini cho bảng xếp hạng.png',
    link: 'https://deepmind.google/technologies/gemini/#introduction',
    userRating: 4.9,
    features: [
      "Độ dài ngữ cảnh (context window) có thể xử lý 1 lần là 1 triệu token",
      "• Tức là có thể xử lý khoảng 1,5 triệu từ hoặc 5.000 trang văn bản trong 1 lần xử lý.",
      "Chỉ số thông minh 70",
      "• Dựa trên trung bình các điểm benmark là",
      "• MMLU-Pro (Reasoning & Knowledge) 86%",
      "• GPQA Diamond (Scientific Reasoning) 84%",
      "• Humanity's Last Exam (Reasoning & Knowledge) 21%",
      "• LiveCodeBench (Coding) 80%",
      "• SciCode (Coding) 43%",
      "• HumanEval (Coding)",
      "• MATH-500 (quantitative reasoning) 97%",
      "• AIME 2024 (Competition Math) 88%",
      "Giá trung bình 3.44 USD / 1 triệu token",
      "• Dựa trên các thông số giá",
      "• Giá đầu vào 1.25 USD / 1 triệu token.",
      "• Giá đầu ra 10 USD / 1 triệu token.",
      "Tốc độ sinh token khá nhanh là 143.9 token /s.",
      "Độ trễ 36.27s là thời gian chờ trung bình từ khi bấm “enter” gửi thông tin đến khi mô hình trả lời token đầu tiên."
    ],
    isFavorite: false,
    contextLengthToken: '1m',
    intelligenceScore: 70,
    pricePerMillionTokens: 3.44,
    speedTokensPerSecond: 143.9,
    latencyFirstChunkSeconds: 36.27,
  },
  {
    id: 'grok-3-mini-reasoning-high',
    name: 'Grok 3 mini Reasoning (high)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'xAI',
    description: `+Grok 3 Mini là mô hình ngôn ngữ mini do xAI phát triển, tích hợp sâu với nền tảng X (Twitter). Phiên bản "Mini" của Grok 3 được tối ưu để giữ được khả năng tuyệt vời khi bật chế độ suy luận cao (reasoning (high)), trong khi vẫn đảm bảo tốc độ phản hồi nhanh và khả năng triển khai nhẹ hơn trên nhiều nền tảng.
+Triển khai linh hoạt: Nhờ dung lượng nhỏ hơn, Grok 3 Mini dễ dàng tích hợp trên nhiều nền tảng, từ web, di động đến các ứng dụng doanh nghiệp.
+ Grok 3 mini do có sự hỗ trợ từ mạng xã hội X (Twitter) từ đó có khả năng truy cập và cập nhật dữ liệu thời gian thực từ X, giúp cung cấp thông tin mới nhất và phù hợp với các sự kiện đang diễn ra .
+ Phong cách phản hồi tự nhiên, thân thiện được học từ những người dùng mạng xã hội X nên Grok 3 và Grok 3 mini được đánh giá rất cao với cách trả lời gần gũi, hài hước và dễ tiếp cận với người dùng Việt Nam.`,
    logoUrl: '/image/Logo Grok cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.8,
    features: [
      "Độ dài ngữ cảnh (context window) có thể xử lý 1 lần là 1 triệu token.",
      "Chỉ số thông minh 67",
      "• Dựa trên trung bình các điểm benmark là",
      "• MMLU-Pro (Reasoning & Knowledge) 83%",
      "• GPQA Diamond (Scientific Reasoning) 79%",
      "• Humanity's Last Exam (Reasoning & Knowledge) 11.1%",
      "• LiveCodeBench (Coding) 70%",
      "• SciCode (Coding) 41%",
      "• HumanEval (Coding) 98%",
      "• MATH-500 (Quantitative reasoning) 99%",
      "• AIME 2024 (Competition Math) 93%",
      "Giá trung bình 0.35 USD / 1 triệu token",
      "• Dựa trên các thông số giá",
      "• Giá đầu vào 0.3 USD / 1 triệu token.",
      "• Giá đầu ra 0.5 USD / 1 triệu token.",
      "Tốc độ sinh token khá nhanh là 209.2 token /s.",
      "Độ trễ 0.32s là thời gian chờ trung bình cực nhanh từ khi bấm “enter” gửi thông tin đến khi mô hình trả lời token đầu tiên."
    ],
    contextLengthToken: '1m',
    intelligenceScore: 67,
    pricePerMillionTokens: 0.35,
    speedTokensPerSecond: 209.2,
    latencyFirstChunkSeconds: 0.32,
  },
  {
    id: 'openai-o4-mini-high',
    name: 'Open AI o4-mini (high)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: `+ OpenAI o4 Mini là phiên bản nhỏ gọn của mô hình ngôn ngữ thế hệ mới OpenAI o4, được thiết kế để cân bằng giữa khả năng suy luận cao cấp và tốc độ phản hồi nhanh, đặc biệt với chế độ suy luận cao (o4-mini-high) dành cho người dùng trả phí giúp xử lý các vấn đề phức tạp với độ chính xác và logic vượt trội.
+ Với dung lượng nhỏ hơn so với phiên bản đầy đủ, o4 Mini dễ dàng tích hợp trên nhiều nền tảng như web, ứng dụng di động và các hệ thống doanh nghiệp, mang lại trải nghiệm mượt mà và phản hồi nhanh chóng, phù hợp với các ứng dụng cần tốc độ và độ chính xác cao.
+ OpenAI o4 Mini được trang bị khả năng sử dụng các công cụ hỗ trợ như tìm kiếm web, xử lý hình ảnh, và các hàm lập trình thông qua API, giúp mô hình có thể truy cập và cập nhật thông tin thời gian thực, cung cấp câu trả lời mới nhất và chính xác nhất cho người dùng.
+ Mô hình được huấn luyện với sự kết hợp của các dữ liệu đa dạng, bao gồm cả các tương tác thực tế, giúp o4 Mini có phong cách trả lời gần gũi, dễ hiểu và thân thiện với người dùng.`,
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.7,
    features: [
      "Độ dài ngữ cảnh (context window) có thể xử lý 1 lần là 200 nghìn token",
      "• Tức là có thể xử lý khoảng 150 nghìn từ hoặc 600 trang văn bản trong 1 lần xử lý.",
      "Chỉ số thông minh 70",
      "• Dựa trên trung bình các điểm benmark là",
      "• MMLU-Pro (Reasoning & Knowledge) 83%",
      "• GPQA Diamond (Scientific Reasoning) 78%",
      "• Humanity's Last Exam (Reasoning & Knowledge) 17.5%",
      "• LiveCodeBench (Coding) 80%",
      "• SciCode (Coding) 47%",
      "• HumanEval (Coding) 99%",
      "• MATH-500 (Quantitative reasoning) 99%",
      "• AIME 2024 (Competition Math) 94%",
      "Giá trung bình 1.93 USD / 1 triệu token",
      "• Dựa trên các thông số giá",
      "• Giá đầu vào 1.1 USD / 1 triệu token.",
      "• Giá đầu ra 4.5 USD / 1 triệu token.",
      "Tốc độ sinh token khá nhanh là 148.0 token /s.",
      "Độ trễ 34.8s là thời gian chờ trung bình từ khi bấm “enter” gửi thông tin đến khi mô hình trả lời token đầu tiên."
    ],
    isFavorite: true,
    contextLengthToken: '200k',
    intelligenceScore: 70,
    pricePerMillionTokens: 1.93,
    speedTokensPerSecond: 148.0,
    latencyFirstChunkSeconds: 34.8,
  },
   {
    id: 'gemini-2.5-flash-reasoning',
    name: 'Gemini 2.5 Flash (Reasoning)',
    type: 'AI Đa phương thức',
    developer: 'Google',
    description: `+ Gemini 2.5 Flash (Reasoning) cập nhật mới nhất là tháng 6-2025 là phiên bản nâng cấp của Gemini 2.0 Flash đặc biệt với chắc năng suy luận nâng cao (Reasoning) mang đến hiệu suất ở mức chấp nhận được kết hợp với chi phí và độ mượt mà.
+ Nâng cấp từ Gemini 2.0 flash nên độ dài ngữ cảnh (context window) ở mức 1 triệu token là mức trở nên bình thường đối với nhà Google.
+ Gemini 2.5 flash đặc biệt phù hợp với các ứng dụng chatbot hoặc web /app cần phản hồi nhanh mà vẫn giữ được sự thông minh. Vì vậy sẽ là đối thủ trực tiếp với Claude 4 Sonnet Thinking nhưng Claude 4 Sonnet có giá chát hơn hẳn.`,
    logoUrl: '/image/Logo Gemini cho bảng xếp hạng.png',
    link: 'https://deepmind.google/technologies/gemini/',
    userRating: 4.9,
    features: ['Suy luận nhanh', 'Hiểu đa phương thức cơ bản', 'Tối ưu hóa tốc độ'],
    contextLengthToken: '1m',
    intelligenceScore: 65,
    pricePerMillionTokens: 0.99,
    speedTokensPerSecond: 330.9,
    latencyFirstChunkSeconds: 16.01,
  },
  {
    id: 'claude-4-opus-thinking',
    name: 'Claude 4 Opus Thinking',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Anthropic',
    description: 'Mô hình mạnh mẽ nhất của Anthropic, mang lại hiệu suất hàng đầu cho các tác vụ rất phức tạp với khả năng suy nghĩ sâu sắc.',
    logoUrl: '/image/Logo Claude AI cho bảng xếp hạng.png',
    link: 'https://www.anthropic.com/news/claude-3-family',
    userRating: 4.9,
    features: ['Phân tích và dự báo nâng cao', 'Tạo nội dung tinh vi', 'Thị giác máy tính'],
    isFavorite: false,
    contextLengthToken: '200k',
    intelligenceScore: 64,
    pricePerMillionTokens: 30.00,
    speedTokensPerSecond: 57.9,
    latencyFirstChunkSeconds: 3.08,
  },
  {
    id: 'openai-o3-mini',
    name: 'Open AI o3-mini (high)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: `+ OpenAI o3 Mini là phiên bản nhỏ gọn của mô hình ngôn ngữ thế hệ mới OpenAI o3, được thiết kế để cân bằng giữa khả năng suy luận cao cấp và tốc độ phản hồi nhanh, đặc biệt với chế độ suy luận cao (o3-mini-high) dành cho người dùng trả phí giúp xử lý các vấn đề phức tạp với độ chính xác và logic vượt trội.
+ Với dung lượng nhỏ hơn so với phiên bản đầy đủ, o3 Mini dễ dàng tích hợp trên nhiều nền tảng như web, ứng dụng di động và các hệ thống doanh nghiệp, mang lại trải nghiệm mượt mà và phản hồi nhanh chóng, phù hợp với các ứng dụng cần tốc độ và độ chính xác cao.
+ OpenAI o3 Mini được trang bị khả năng sử dụng các công cụ hỗ trợ như tìm kiếm web, xử lý hình ảnh, và các hàm lập trình thông qua API, giúp mô hình có thể truy cập và cập nhật thông tin thời gian thực, cung cấp câu trả lời mới nhất và chính xác nhất cho người dùng.
+ Mô hình được huấn luyện với sự kết hợp của các dữ liệu đa dạng, bao gồm cả các tương tác thực tế, giúp o3 Mini có phong cách trả lời gần gũi, dễ hiểu và thân thiện với người dùng.`,
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.9,
    features: [
      "Độ dài ngữ cảnh (context window) có thể xử lý một lần là 200 nghìn token",
      "• Tức là có thể xử lý khoảng 150 nghìn từ hoặc 600 trang văn bản trong 1 lần xử lý.",
      "Chỉ số thông minh 66",
      "• Dựa trên trung bình các điểm benmark là",
      "• MMLU-Pro (Reasoning & Knowledge) 80%",
      "• GPQA Diamond (Scientific Reasoning) 77%",
      "• Humanity's Last Exam (Reasoning & Knowledge) 12.3%",
      "• LiveCodeBench (Coding) 73%",
      "• SciCode (Coding) 40%",
      "• HumanEval (Coding) 98%",
      "• MATH-500 (Quantitative reasoning) 99%",
      "• AIME 2024 (Competition Math) 86%",
      "Giá trung bình 1.93 USD / 1 triệu token",
      "• Dựa trên các thông số giá",
      "• Giá đầu vào 1.1 USD / 1 triệu token.",
      "• Giá đầu ra 4.4 USD / 1 triệu token.",
      "Tốc độ sinh token là 151.2 token /s.",
      "Độ trễ 48.85s là thời gian chờ trung bình từ khi bấm “enter” gửi thông tin đến khi mô hình trả lời token đầu tiên."
    ],
    contextLengthToken: '200k',
    intelligenceScore: 66,
    pricePerMillionTokens: 1.93,
    speedTokensPerSecond: 151.2,
    latencyFirstChunkSeconds: 48.85,
  },
  {
    id: 'qwen3-235b-reasoning',
    name: 'Qwen3 235B (Reasoning)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Alibaba',
    description: 'Mô hình Qwen3 235B của Alibaba với khả năng suy luận nâng cao.',
    logoUrl: '/image/Logo Qwen cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.9,
    features: ['Khả năng suy luận đa bước', 'Hỗ trợ đa ngôn ngữ', 'Kiến thức rộng'],
    contextLengthToken: '128k',
    intelligenceScore: 60,
    pricePerMillionTokens: 2.63,
    speedTokensPerSecond: 70.5,
    latencyFirstChunkSeconds: 1.17,
  },
  {
    id: 'openai-o1',
    name: 'Open AI o1',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'Mô hình Open AI o1 từ OpenAI.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.9,
    features: ['Mô hình cơ sở mạnh mẽ', 'Lý luận chung', 'Tạo văn bản'],
    contextLengthToken: '200k',
    intelligenceScore: 62,
    pricePerMillionTokens: 26.25,
    speedTokensPerSecond: 171.9,
    latencyFirstChunkSeconds: 17.43,
  },
  {
    id: 'llama-nemotron-ultra-reasoning',
    name: 'Llama Nemotron Ultra Reasoning',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Nvidia',
    description: 'Mô hình Llama Nemotron Ultra Reasoning từ Nvidia, tối ưu cho suy luận.',
    logoUrl: '/image/Logo Llama Nemotron Ultra Reasoning cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.9,
    features: ['Suy luận tiên tiến', 'Tối ưu hóa phần cứng Nvidia', 'Khả năng mở rộng'],
    contextLengthToken: '128k',
    intelligenceScore: 61,
    pricePerMillionTokens: 0.90,
    speedTokensPerSecond: 42,
    latencyFirstChunkSeconds: 0.64,
  },
  {
    id: 'claude-4-sonnet-thinking',
    name: 'Claude 4 Sonnet Thinking',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Anthropic',
    description: 'Mô hình Claude 4 Sonnet Thinking từ Anthropic với khả năng suy nghĩ.',
    logoUrl: '/image/Logo Claude AI cho bảng xếp hạng.png',
    link: 'https://www.anthropic.com/news/claude-3-family',
    userRating: 4.9,
    features: ['Cân bằng hiệu suất và tốc độ', 'Mạnh mẽ trong các tác vụ doanh nghiệp', 'An toàn và đáng tin cậy'],
    contextLengthToken: '200k',
    intelligenceScore: 61,
    pricePerMillionTokens: 6.00,
    speedTokensPerSecond: 60.8,
    latencyFirstChunkSeconds: 1.28,
  },
  {
    id: 'deepseek-r1-jan25',
    name: 'DeepSeek R1 (Tháng 1-25)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Deepseek',
    description: 'Mô hình DeepSeek R1, phiên bản tháng 1-25.',
    logoUrl: '/image/Logo Deepseek cho bảng xếp hạng.png',
    link: 'https://www.deepseek.com/',
    userRating: 4.9,
    features: ['Khả năng viết mã mạnh mẽ', 'Hiểu biết ngôn ngữ sâu', 'Mô hình nguồn mở'],
    contextLengthToken: '128k',
    intelligenceScore: 60,
    pricePerMillionTokens: 2.36,
    speedTokensPerSecond: undefined,
    latencyFirstChunkSeconds: undefined,
  },
  {
    id: 'openai-o1-preview',
    name: 'Open AI o1-preview',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'Phiên bản xem trước của mô hình Open AI o1.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.9,
    features: ['Truy cập sớm vào các tính năng mới', 'Mô hình mạnh mẽ', 'Dành cho nhà phát triển'],
    contextLengthToken: '128k',
    intelligenceScore: 60,
    pricePerMillionTokens: 26.25,
    speedTokensPerSecond: 141.4,
    latencyFirstChunkSeconds: 26.13,
  },
  {
    id: 'qwen3-14b-reasoning',
    name: 'Qwen3 14B (Reasoning)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Alibaba',
    description: 'Mô hình Qwen3 14B từ Alibaba, tối ưu cho suy luận.',
    logoUrl: '/image/Logo Qwen cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.9,
    features: ['Kích thước mô hình nhỏ gọn', 'Hiệu quả cho suy luận', 'Hỗ trợ đa ngôn ngữ'],
    contextLengthToken: '128k',
    intelligenceScore: 62,
    pricePerMillionTokens: 1.31,
    speedTokensPerSecond: 65.5,
    latencyFirstChunkSeconds: 1.05,
  },
  {
    id: 'qwen3-32b-reasoning',
    name: 'Qwen3 32B (Reasoning)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Alibaba',
    description: 'Mô hình Qwen3 32B từ Alibaba, tối ưu cho suy luận.',
    logoUrl: '/image/Logo Qwen cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.9,
    features: ['Hiệu suất suy luận tốt', 'Hỗ trợ đa ngôn ngữ', 'Dòng mô hình Qwen'],
    contextLengthToken: '128k',
    intelligenceScore: 59,
    pricePerMillionTokens: 2.63,
    speedTokensPerSecond: 61.6,
    latencyFirstChunkSeconds: 1.09,
  },
  {
    id: 'qwenq-32b',
    name: 'QwenQ-32B',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Alibaba',
    description: 'Mô hình QwenQ-32B từ Alibaba.',
    logoUrl: '/image/Logo Qwen cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.9,
    features: ['Biến thể của dòng Qwen', 'Tối ưu hóa cho các tác vụ cụ thể', 'Hiệu suất cao'],
    contextLengthToken: '131k',
    intelligenceScore: 56,
    pricePerMillionTokens: 0.63,
    speedTokensPerSecond: 92.9,
    latencyFirstChunkSeconds: 0.4,
  },
  {
    id: 'claude-4-opus',
    name: 'Claude 4 Opus',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Anthropic',
    description: 'Mô hình Claude 4 Opus của Anthropic, với hiệu suất cao và khả năng lý luận sâu sắc.',
    logoUrl: '/image/Logo Claude AI cho bảng xếp hạng.png',
    link: 'https://www.anthropic.com/news/claude-3-family',
    userRating: 4.9,
    features: ['Khả năng lý luận hàng đầu', 'Hiểu biết sâu sắc', 'Tập trung vào an toàn'],
    isFavorite: false,
    contextLengthToken: '200k',
    intelligenceScore: 58,
    pricePerMillionTokens: 30.00,
    speedTokensPerSecond: 54.3,
    latencyFirstChunkSeconds: 3.01,
  },
  {
    id: 'claude-3.7-sonnet-thinking',
    name: 'Claude 3.7 Sonnet Thinking',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Anthropic',
    description: 'Mô hình Claude 3.7 Sonnet Thinking của Anthropic.',
    logoUrl: '/image/Logo Claude AI cho bảng xếp hạng.png',
    link: 'https://www.anthropic.com/news/claude-3-5-sonnet',
    userRating: 4.9,
    features: ['Phiên bản cải tiến của Sonnet', 'Tăng cường khả năng suy nghĩ', 'Cân bằng giữa hiệu suất và tốc độ'],
    contextLengthToken: '200k',
    intelligenceScore: 57,
    pricePerMillionTokens: 6.00,
    speedTokensPerSecond: 87.5,
    latencyFirstChunkSeconds: 1.08,
  },
  {
    id: 'openai-o3',
    name: 'Open AI o3',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: `+ OpenAI o3 là mô hình ngôn ngữ thế hệ mới do OpenAI phát triển, được ra mắt chính thức vào cuối năm 2024 như một bước tiến vượt bậc so với phiên bản tiền nhiệm o1. Đây là một mô hình transformer phản chiếu (reflective generative pre-trained transformer) được thiết kế đặc biệt để xử lý các câu hỏi đòi hỏi suy luận logic nhiều bước và tư duy phân tích sâu sắc
+ OpenAI o3 là một trong những mô hình đầu tiên của OpenAI có khả năng sử dụng công cụ một cách tự động trong quy trình suy luận, từ đó có thể truy cập thông tin thời gian thực, phân tích dữ liệu phức tạp và phối hợp nhiều khả năng để giải quyết các vấn đề đa bước hiệu quả hơn.
+ OpenAI o3 đã áp dụng các kỹ thuật điều chỉnh và kiểm soát mới nhằm giảm thiểu các kết quả gây hại hoặc thiên lệch, đồng thời nâng cao tính minh bạch trong quá trình suy luận của mô hình.
+ Mô hình cũng được tích hợp trong các dịch vụ như ChatGPT, API, Playground`,
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.9,
    features: [
      "Độ dài ngữ cảnh (context window) có thể xử lý một lần là 200 nghìn token",
      "• Tức là có thể xử lý khoảng 150 nghìn từ hoặc 600 trang văn bản trong 1 lần xử lý.",
      "Chỉ số thông minh 70",
      "• Dựa trên trung bình các điểm benmark là",
      "• MMLU-Pro (Reasoning & Knowledge) 85%",
      "• GPQA Diamond (Scientific Reasoning) 83%",
      "• Humanity's Last Exam (Reasoning & Knowledge) 20%",
      "• LiveCodeBench (Coding) 78%",
      "• SciCode (Coding) 41%",
      "• HumanEval (Coding) 99%",
      "• MATH-500 (Quantitative reasoning) 99%",
      "• AIME 2024 (Competition Math) 90%",
      "Giá trung bình 3.5 USD / 1 triệu token",
      "• Dựa trên các thông số giá",
      "• Giá đầu vào 2.0 USD / 1 triệu token.",
      "• Giá đầu ra 8.0 USD / 1 triệu token.",
      "Tốc độ sinh token là 117.0 token /s.",
      "Độ trễ 22.17s là thời gian chờ trung bình từ khi bấm “enter” gửi thông tin đến khi mô hình trả lời token đầu tiên."
    ],
    isFavorite: false,
    contextLengthToken: '200k',
    intelligenceScore: 70,
    pricePerMillionTokens: 3.5,
    speedTokensPerSecond: 117.0,
    latencyFirstChunkSeconds: 22.17,
  },
  {
    id: 'grok-3-reasoning-beta',
    name: 'Grok 3 Reasoning Beta',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'xAI',
    description: 'Phiên bản Beta của Grok 3 Reasoning.',
    logoUrl: '/image/Logo Grok cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.9,
    features: ['Truy cập sớm vào khả năng suy luận Grok 3', 'Tích hợp dữ liệu thời gian thực từ X', 'Phong cách hài hước'],
    contextLengthToken: '1m',
    intelligenceScore: 56,
    pricePerMillionTokens: 0.00,
    speedTokensPerSecond: undefined,
    latencyFirstChunkSeconds: undefined,
  },
  {
    id: 'qwen3-30b-a3b-reasoning',
    name: 'Qwen3 30B A3B (Reasoning)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Alibaba',
    description: 'Mô hình Qwen3 30B A3B từ Alibaba, tối ưu cho suy luận.',
    logoUrl: '/image/Logo Qwen cho bảng xếp hạng.png',
    link: '#',
    userRating: 4.9,
    features: ['Biến thể cụ thể của Qwen3 30B', 'Tối ưu hóa cho suy luận A3B', 'Hiệu suất cao'],
    contextLengthToken: '128k',
    intelligenceScore: 56,
    pricePerMillionTokens: 0.75,
    speedTokensPerSecond: 92.2,
    latencyFirstChunkSeconds: 1.01,
  },
  {
    id: 'claude-4-sonnet',
    name: 'Claude 4 Sonnet',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Anthropic',
    description: 'Mô hình Claude 4 Sonnet, sự cân bằng giữa trí thông minh và tốc độ cho khối lượng công việc của doanh nghiệp.',
    logoUrl: '/image/Logo Claude AI cho bảng xếp hạng.png',
    link: 'https://www.anthropic.com/news/claude-3-family',
    userRating: 4.5,
    features: ['Hiệu suất đáng tin cậy', 'Tốc độ cao', 'Lý luận phức tạp'],
    isFavorite: false,
    contextLengthToken: '200k',
    intelligenceScore: 53,
    pricePerMillionTokens: 6.00,
    speedTokensPerSecond: 62.9,
    latencyFirstChunkSeconds: 1.49,
  },
  {
    id: 'gpt-4.5-preview',
    name: 'GPT-4.5 (Preview)',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'Phiên bản xem trước của GPT-4.5, cung cấp các cải tiến so với các mô hình trước đó.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.5,
    features: ['Khả năng nâng cao', 'Cửa sổ ngữ cảnh lớn hơn', 'Truy cập sớm'],
    isFavorite: false,
    contextLengthToken: '128k',
    intelligenceScore: 53,
    pricePerMillionTokens: 93.75,
    speedTokensPerSecond: 81.9,
    latencyFirstChunkSeconds: 0.92,
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 mini',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'Một phiên bản nhỏ gọn hơn của GPT-4.1, được tối ưu hóa cho hiệu quả và tốc độ.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.5,
    features: ['Hiệu quả chi phí', 'Tốc độ phản hồi nhanh', 'Lý luận mạnh mẽ'],
    isFavorite: false,
    contextLengthToken: '1m',
    intelligenceScore: 53,
    pricePerMillionTokens: 0.70,
    speedTokensPerSecond: 72.9,
    latencyFirstChunkSeconds: 0.43,
  },
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'Một mô hình mạnh mẽ trong dòng GPT-4, cung cấp khả năng lý luận và hiểu biết mạnh mẽ.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/',
    userRating: 4.5,
    features: ['Lý luận nâng cao', 'Hiểu biết ngữ cảnh sâu', 'Tạo văn bản chất lượng cao'],
    isFavorite: false,
    contextLengthToken: '1m',
    intelligenceScore: 53,
    pricePerMillionTokens: 3.50,
    speedTokensPerSecond: 112.0,
    latencyFirstChunkSeconds: 0.48,
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'xAI',
    description: 'Mô hình Grok 3 từ xAI, được biết đến với khả năng truy cập thông tin thời gian thực và phong cách phản hồi độc đáo.',
    logoUrl: '/image/Logo Grok cho bảng xếp hạng.png',
    link: 'https://x.ai/grok',
    userRating: 4.4,
    features: ['Truy cập thông tin thời gian thực', 'Hiểu biết sâu rộng', 'Phong cách trò chuyện độc đáo'],
    isFavorite: false,
    contextLengthToken: '1m',
    intelligenceScore: 51,
    pricePerMillionTokens: 6.00,
    speedTokensPerSecond: 90.3,
    latencyFirstChunkSeconds: 0.41,
  },
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'Meta',
    description: 'Mô hình Llama 4 Maverick từ Meta, một phần của dòng mô hình Llama mã nguồn mở mạnh mẽ.',
    logoUrl: '/image/Logo LLMA cho bảng xếp hạng.png',
    link: 'https://ai.meta.com/llama/',
    userRating: 4.4,
    features: ['Mã nguồn mở', 'Hiệu suất cao', 'Khả năng tùy chỉnh'],
    isFavorite: false,
    contextLengthToken: '1m',
    intelligenceScore: 51,
    pricePerMillionTokens: 0.39,
    speedTokensPerSecond: 166.1,
    latencyFirstChunkSeconds: 0.33,
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    type: 'Mô hình ngôn ngữ lớn',
    developer: 'OpenAI',
    description: 'Mô hình GPT-4o ("omni") của OpenAI, mang đến khả năng đa phương thức và hiệu suất cao.',
    logoUrl: '/image/Logo Open AI cho bảng xếp hạng.png',
    link: 'https://openai.com/gpt-4o',
    userRating: 4.3,
    features: ['Đa phương thức (văn bản, âm thanh, hình ảnh)', 'Tốc độ phản hồi nhanh hơn', 'Cải thiện khả năng hiểu'],
    isFavorite: false,
    contextLengthToken: '128k',
    intelligenceScore: 50,
    pricePerMillionTokens: 7.50,
    speedTokensPerSecond: 168.6,
    latencyFirstChunkSeconds: 0.45,
  }
];


export const mockNews: NewsArticle[] = [
  {
    id: 'news1',
    title: 'Claude 3 Opus Giành Vị trí Dẫn đầu trong Đấu trường AI, Vượt qua GPT-4',
    source: 'Anthropic',
    content: 'Mô hình mới nhất của Anthropic, Claude 3 Opus, đã chứng minh hiệu suất vượt trội trong các bài kiểm tra khác nhau, có khả năng vượt qua GPT-4 của OpenAI trong các lĩnh vực quan trọng về lý luận và kiến thức.',
    publishedAt: '2025-06-08T10:00:00Z',
    imageUrl: 'https://placehold.co/400x225.png',
    link: '#',
    dataAiHint: 'AI model'
  },
  {
    id: 'news2',
    title: 'Tương lai của AI trong Chăm sóc Sức khỏe: Dự đoán cho năm 2025',
    source: 'Tech Journal',
    content: 'Các chuyên gia dự đoán AI sẽ cách mạng hóa chẩn đoán, y học cá nhân hóa và khám phá thuốc trong vài năm tới, dẫn đến việc chăm sóc sức khỏe hiệu quả hơn.',
    publishedAt: '2025-06-07T14:30:00Z',
    imageUrl: 'https://placehold.co/400x225.png',
    link: '#',
    dataAiHint: 'AI healthcare'
  },
  {
    id: 'news3',
    title: 'AI Đạo đức: Điều hướng các Thách thức về Thiên vị và Minh bạch',
    source: 'AI Ethics Weekly',
    content: 'Khi các hệ thống AI ngày càng được tích hợp vào xã hội, việc giải quyết các vấn đề về thiên vị, công bằng và minh bạch là rất quan trọng để phát triển và triển khai có trách nhiệm.',
    publishedAt: '2025-06-06T09:15:00Z',
    imageUrl: 'https://placehold.co/400x225.png',
    link: '#',
    dataAiHint: 'AI ethics'
  },
];
