// src/components/news/charts/ChartBar.tsx
"use client";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, LabelList } from 'recharts';
import type { ChartComponentProps } from '@/types/chart';

export function ChartBar({ config }: { config: any }) {
  const { data, dataKeys, indexKey, unit } = config;

  // Fallback in case dataKeys is not generated by the adapter
  const keysToRender = dataKeys || (data[0] ? Object.keys(data[0]).filter(k => k !== indexKey && k !== 'color') : []);

  return (
    <ResponsiveContainer width="100%" height={350}>
      <BarChart data={data} margin={{ top: 20, right: 30, left: 0, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" vertical={false} />
        
        <XAxis 
          dataKey={indexKey} 
          fontSize={12} 
          tickLine={false} 
          axisLine={false} 
          dy={10}
          tick={{ fontWeight: 'bold' }}
        />
        
        <YAxis 
          fontSize={12} 
          tickFormatter={(value) => `${value}${unit}`} 
        />

        <Tooltip 
          formatter={(value: any, name: string) => [`${value}${unit}`, name]}
          contentStyle={{ 
            borderRadius: '8px', 
            backgroundColor: 'hsl(var(--background))',
            borderColor: 'hsl(var(--border))'
          }}
          cursor={{ fill: 'hsl(var(--accent))' }}
        />
        <Legend verticalAlign="top" height={40} />
        
        {keysToRender.map((key: any, index: number) => (
          <Bar key={key.name || key} dataKey={key.name || key} fill={key.color || config.colors[index] || '#8884d8'} radius={[4, 4, 0, 0]}>
            <LabelList 
              dataKey={key.name || key} 
              position="top" 
              fontSize={11} 
              className="fill-foreground"
              formatter={(val: any) => `${val}${unit}`} // Hiện đơn vị trên đầu cột
            />
          </Bar>
        ))}
      </BarChart>
    </ResponsiveContainer>
  );
}
